// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
// 全局声明组件s

declare module 'vue' {
  export interface GlobalComponents {
    Beehive: typeof import('./src/components/content/beehive/Beehive.vue')['default']
    BlogNav: typeof import('./src/components/content/blognav/blogNav.vue')['default']
    Calendar: typeof import('./src/components/content/calendar/Calendar.vue')['default']
    CircleChart: typeof import('./src/components/content/circlechart/CircleChart.vue')['default']
    ContentBackground: typeof import('./src/components/content/background/ContentBackground.vue')['default']
    Cube: typeof import('./src/components/content/animation/Cube.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    LineChart: typeof import('./src/components/content/linechart/LineChart.vue')['default']
    NavBar: typeof import('./src/components/content/navbar/NavBar.vue')['default']
    Particles: typeof import('./src/components/content/particles/Particles.vue')['default']
    Progress: typeof import('./src/components/content/progress/Progress.vue')['default']
    Snake: typeof import('./src/components/content/snake/Snake.vue')['default']
    TimeLine: typeof import('./src/components/content/timeline/TimeLine.vue')['default']
    ToDoList: typeof import('./src/components/content/todolist/ToDoList.vue')['default']
    TopBackGround: typeof import('./src/components/content/background/TopBackGround.vue')['default']
    Turntable: typeof import('./src/components/content/turntable/Turntable.vue')['default']
    Vue2Record: typeof import('./src/components/content/vue2record/vue2Record.vue')['default']
    Vue3Record: typeof import('./src/components/content/vue3record/vue3Record.vue')['default']
    WeekTodo: typeof import('./src/components/content/weektodo/WeekTodo.vue')['default']
    Windmill: typeof import('./src/components/content/animation/Windmill.vue')['default']
  }
}

export { }
